objects+=src/IBConfig.o src/bcm2835.o
gtk_objects+=src/IBGui.o
gtk_private_o+=src/resources.o
binaries+=cmdline_local bcm2835.pwmexample bcm2835.blink
gtk_binaries+=gui_local gui_remote
generated+=include/resources.h src/resources.cpp
CFLAGS+=`pkg-config --cflags gtk+-3.0`
CFLAGS+=-g

include ../Makerules.inc
all:Makefile.inc
