private_objects+= src/klaus_i2c_iface.o src/HistogramDAQ_server.o
objects+= src/DAQ_Main_Frame_local.o
dict_headers+= include/DAQ_Main_Frame_local.h
#binaries+= klaus_i2c_dump klaus_i2c_dump_text klaus_i2c_histserver i2c_write2txt
binaries+= klaus_i2c_daqserver klaus_i2c_cectest
binaries+= daq_gui_local
CFLAGS+=-Iinclude `root-config --cflags` -std=c++11 -fPIC

include ../Makerules.inc
all:Makefile.inc
