all: all_
include ../daq-common/Makefile.inc
include ../chip-interfaces/Makefile.inc
include ../chip-interfaces-remote/Makefile.inc
include ../config-k4/Makefile.inc
include Makefile.configure
all_: gen obj bin

